version: '3'  

services:
  adguardhome:  # Define the service named 'adguardhome'
    image: adguard/adguardhome  # Use the 'adguard/adguardhome' Docker image
    container_name: adguardhome  # Set the container name to 'adguardhome'
    restart: unless-stopped  # Restart the container automatically unless stopped manually
    ports:  
      # Expose port 53 on TCP and UDP for DNS queries
      - "53:53/tcp"
      - "53:53/udp"

      # Expose port 3000 on TCP for AdGuard Home's API
      - "3000:3000/tcp"
      
      # Expose port 5443 on TCP and UDP for DNSCrypt
      - "5443:5443/tcp"
      - "5443:5443/udp"

      
    volumes:
      - /data/adguard/work:/opt/adguardhome/work  
      - /data/adguard/confdir:/opt/adguardhome/conf  
