version: "3.8"

services:
  cloudbeaver:
      network: host
      image: dbeaver/cloudbeaver:latest
      container_name: "dbeaver"
      restart: always
      ports:
       - '8978:8978'
      volumes: 
       - /data/cloudbeaver:/opt/cloudbeaver/workspace            
