services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:v1.19.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /volume1/docker/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=babb0191f7c0f123456792591beab176718349bbfe61da9a81b20706624e6b95
    ports:
      - '7575:7575'
