services:
    semaphore:
        ports:
            - 3000:3000
        image: semaphoreui/semaphore:v2.15.0
        environment:
            SEMAPHORE_DB_DIALECT: bolt
            SEMAPHORE_ADMIN: admin
            SEMAPHORE_ADMIN_PASSWORD: changeme
            SEMAPHORE_ADMIN_NAME: Admin
            SEMAPHORE_ADMIN_EMAIL: admin@localhost
        volumes:
            - /data/semaphore:/var/lib/semaphore
volumes:
    /data/semaphore:
